#!/bin/bash
# This deploy hook gets executed after dependencies are resolved and the
# build hook has been run but before the application has been started back
# up again.  This script gets executed directly, so it could be python, php,
# ruby, etc.

# Activate VirtualEnv in order to use the correct libraries
source "$OPENSHIFT_HOMEDIR/python-2.6/virtenv/bin/activate"

# set up common env
source $OPENSHIFT_REPO_DIR/common.env

echo "Executing django-admin.py syncdb --noinput"
django-admin.py syncdb --noinput

echo "Executing django-admin.py migrate"
django-admin.py migrate
